Use debouncer to handle button analysis
adafruit/Adafruit_CircuitPython_CursorControl pull request #3
Opened 2019-07-02 20:29 UTC by dastels

2019-07-02 20:39 UTC, brentru requested changes
@dastels  The response time to quick double-clicks seems slow and misses. 

Could you add getter/setter methods called `debounce_interval` which increase the debouncer's `interval` property?

2019-07-02 21:06 UTC, brentru requested changes

2019-07-02 21:06 UTC, brentru commented on adafruit_cursorcontrol/cursorcontrol_cursormanager.py
> +    """Simple interaction user interface interaction for Adafruit_CursorControl.
Could you explain the purpose of `DebouncedCursorManager` here? 

This is how you mentioned the `DebouncedCursorManager` works to me: 
> The one with the debouncer would provide the additional press, release, is_pressed functionallity

2019-07-02 21:06 UTC, brentru commented on adafruit_cursorcontrol/cursorcontrol_cursormanager.py
> +    pressed = is_clicked
indent this

2019-07-02 22:41 UTC, dastels commented
Do we really want/need accessors for the debouncer interval, or is passing it as a constructor argument enough?

2019-07-03 14:28 UTC, brentru commented
@dastels  I think it's OK as a kwarg.

2019-07-03 14:33 UTC, brentru approved these changes

2019-07-03 14:33 UTC, merged